name: jobgen
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - attrs=24.3.0
  - backcall=0.2.0
  - beautifulsoup4=4.13.4
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - certifi=2025.8.3
  - click=8.1.7
  - comm=0.2.3
  - contourpy=1.3.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - fontconfig=2.15.0
  - fonttools=4.59.1
  - freetype=2.13.3
  - giflib=5.2.2
  - greenlet=3.1.1
  - icu=73.2
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2022.1.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - keyutils=1.6.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.12
  - ld_impl_linux-64=2.44
  - lerc=2.2.1
  - libabseil=20250127.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcups=2.4.2
  - libcurl=8.15.0
  - libdeflate=1.7
  - libdrm=2.4.125
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libkrb5=1.21.3
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.2.0
  - libuuid=2.41.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - mesalib=25.0.5
  - mistune=3.1.2
  - mkl=2022.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nltk=3.9.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - olefile=0.47
  - openjpeg=2.1.0
  - openldap=2.6.4
  - openssl=3.5.4
  - orjson=3.10.14
  - packaging=25.0
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=25.2
  - platformdirs=4.3.8
  - ply=3.11
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.9.23
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2024.1
  - pyzmq=27.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.11.6
  - rpds-py=0.22.3
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - soupsieve=2.5
  - spirv-tools=2025.1
  - sqlalchemy=2.0.37
  - sqlite=3.50.4
  - sqlparse=0.5.2
  - stack_data=0.6.3
  - tabulate=0.9.0
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tikzplotlib=0.10.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - adjusttext==1.3.0
      - charset-normalizer==3.4.2
      - dill==0.3.9
      - dotenv==0.9.9
      - filelock==3.18.0
      - fsspec==2025.5.1
      - hf-xet==1.1.4
      - huggingface-hub==0.33.0
      - idna==3.10
      - inquirerpy==0.3.4
      - klepto==0.2.6
      - mo-dots==4.22.21108
      - mo-future==3.147.20327
      - mo-imports==3.149.20327
      - mo-kwargs==4.22.21108
      - mo-logs==4.23.21108
      - moz-sql-parser==4.40.21126
      - pathlib==1.0.1
      - pfzy==0.3.4
      - pglast==7.7
      - pox==0.3.5
      - pygtrie==2.5.0
      - python-dotenv==1.2.1
      - pyyaml==6.0.2
      - requests==2.32.4
      - seaborn==0.13.2
      - toml==0.10.2
      - urllib3==2.4.0
