neo_args:
  logdir: runs/logs/neo_job_d
  baseline_path: runs/job_d/postgresql/optimizer/
  latency: true
  reward_weighting: false
  cost_func: 'no_op'
  n_workers: 8
  num_complete_plans: 5
  sync: true
  total_episodes: 100
  val_size: 20
  encoding: 'neo'
  selectivity: false
  eps: 0
  device: cuda
net_args:
  d_emb: 21 # 22 for selectivity
  d_query: 318 #642 for rtos; 318 for neo encoding
  drop: 0.03
train_args:
  batch_size: 100
  epochs: 100
  betas:
  - 0.245543
  - 0.4175792
  lr: 0.0005
  scheduler: 0.776
