name: balsa
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _pytorch_select=0.2
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2024.8.30
  - cffi=1.15.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - expat=2.7.1
  - faiss=1.7.0
  - faiss-gpu=1.7.0
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.13.3
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - greenlet=2.0.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - intel-openmp=2025.0.0
  - jpeg=9f
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.8.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libfaiss=1.7.0
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - liblapack=3.8.0
  - libllvm14=14.0.6
  - libnsl=2.0.1
  - libpng=1.6.39
  - libpq=12.20
  - libsqlite=3.45.2
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.17.0
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - ninja=1.12.1
  - ninja-base=1.12.1
  - nspr=4.35
  - nss=3.89.1
  - numpy-base=1.19.2
  - openssl=3.5.0
  - pcre2=10.42
  - pillow=9.4.0
  - pip=22.3.1
  - ply=3.11
  - pthread-stubs=0.3
  - pudb=2022.1.3
  - pycparser=2.21
  - pyparsing=2.4.7
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.7.12
  - python_abi=3.7
  - pytorch=1.4.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - setuptools=65.6.3
  - sip=6.6.2
  - sqlalchemy=1.4.39
  - sqlite=3.45.2
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.2
  - typing_extensions=4.4.0
  - urwid=2.1.2
  - urwid_readline=0.15.1
  - wheel=0.38.4
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - absl-py==0.9.0
      - aiohttp==3.7.4
      - aiopg==1.3.5
      - aioredis==1.3.1
      - async-timeout==3.0.1
      - attrs==24.2.0
      - backcall==0.2.0
      - cachetools==4.2.4
      - chardet==3.0.4
      - charset-normalizer==3.4.1
      - click==8.1.8
      - decorator==5.1.1
      - deprecated==1.2.18
      - docker-pycreds==0.4.0
      - dotenv==0.9.9
      - filelock==3.12.2
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.43.0
      - hiredis==2.3.2
      - idna==3.10
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipdb==0.13.13
      - ipython==7.34.0
      - jedi==0.19.2
      - jsonschema==4.17.3
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.6
      - msgpack==1.0.5
      - multidict==6.0.5
      - networkx==2.6.3
      - numpy==1.18.1
      - oauthlib==3.2.2
      - packaging==24.0
      - pandas==1.3.5
      - parso==0.8.4
      - pathlib==1.0.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.0.0
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - psutil==6.1.1
      - psycopg2-binary==2.8.5
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygments==2.17.2
      - pyrsistent==0.19.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==0.21.1
      - pytorch-lightning==0.9.0
      - pytz==2024.2
      - pyyaml==6.0.1
      - ray==1.9.2
      - redis==4.1.4
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - sentry-sdk==2.20.0
      - setproctitle==1.3.3
      - six==1.17.0
      - smmap==5.0.2
      - tensorboard==2.2.0
      - tensorboard-plugin-wit==1.8.1
      - tomli==2.0.1
      - tqdm==4.67.1
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - wandb==0.18.7
      - wcwidth==0.2.13
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.15.0
