name: fastgres
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - ca-certificates=2025.2.25
  - cyrus-sasl=2.1.28
  - greenlet=3.1.1
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libpq=17.2
  - libstdcxx-ng=11.2.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=2.0.2
  - numpy-base=2.0.2
  - openldap=2.6.4
  - openssl=3.0.16
  - orjson=3.10.14
  - pandas=2.2.3
  - pip=24.2
  - psycopg2=2.9.9
  - pybind11-abi=4
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=72.1.0
  - six=1.16.0
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tqdm=4.66.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - about-time==4.2.1
      - alive-progress==3.2.0
      - dotenv==0.9.9
      - grapheme==0.6.0
      - mo-dots==10.659.25005
      - mo-future==7.584.24095
      - mo-imports==7.584.24095
      - mo-parsing==8.661.25011
      - mo-sql-parsing==11.663.25011
      - pathlib==1.0.1
      - pickle5==0.0.11
      - psycopg2-binary==2.9.10
      - python-dotenv==1.2.1
