name: base_opt
channels:
  - pytorch
  - nvidia/label/cuda-12.1.1
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - binutils=2.40
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cccl=2.3.2
  - cuda=12.1.0
  - cuda-cccl=12.4.127
  - cuda-cccl_linux-64=12.4.127
  - cuda-command-line-tools=12.1.1
  - cuda-compiler=12.4.1
  - cuda-crt-dev_linux-64=12.4.131
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-dev_linux-64=12.4.127
  - cuda-cudart-static=12.4.127
  - cuda-cudart-static_linux-64=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cuobjdump=12.4.127
  - cuda-cupti=12.1.105
  - cuda-cuxxfilt=12.4.127
  - cuda-demo-suite=12.1.105
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.4.127
  - cuda-driver-dev_linux-64=12.4.127
  - cuda-gdb=12.4.127
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.6.2
  - cuda-libraries-static=12.6.2
  - cuda-nsight=12.4.127
  - cuda-nvcc=12.4.131
  - cuda-nvcc-dev_linux-64=12.4.131
  - cuda-nvcc-tools=12.4.131
  - cuda-nvcc_linux-64=12.1.1
  - cuda-nvdisasm=12.4.127
  - cuda-nvml-dev=12.4.127
  - cuda-nvprof=12.4.127
  - cuda-nvprune=12.4.127
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvrtc-static=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-nvvm-dev_linux-64=12.4.131
  - cuda-nvvm-impl=12.4.131
  - cuda-nvvm-tools=12.4.131
  - cuda-nvvp=12.4.127
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-runtime=12.1.0
  - cuda-sanitizer-api=12.4.127
  - cuda-toolkit=12.1.0
  - cuda-tools=12.1.1
  - cuda-version=12.4
  - cuda-visual-tools=12.6.2
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.4
  - filelock=3.13.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gds-tools=1.9.1.3
  - gensim=4.3.3
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - joblib=1.4.2
  - kernel-headers_linux-64=3.10.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcublas-static=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcufft-static=11.0.2.4
  - libcufile=1.9.1.3
  - libcufile-dev=1.9.1.3
  - libcufile-static=1.9.1.3
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurand-static=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusolver-static=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libcusparse-static=12.0.2.55
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnpp-static=12.0.2.50
  - libnvfatbin=12.4.127
  - libnvfatbin-dev=12.4.127
  - libnvfatbin-static=12.4.127
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjitlink-static=12.4.127
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libnvjpeg-static=12.1.1.14
  - libnvvm-samples=12.1.105
  - libpng=1.6.39
  - libpq=17.2
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.4.2
  - nsight-compute=2024.1.1.4
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openldap=2.6.4
  - openssl=3.0.16
  - pcre2=10.42
  - pip=25.0
  - psycopg2=2.9.9
  - pybind11-abi=5
  - python=3.12.8
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=72.1.0
  - smart_open=5.2.1
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - sympy=1.13.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchtriton=3.1.0
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - dotenv==0.9.9
      - pathlib==1.0.1
      - python-dotenv==1.2.1
      - sql-metadata==2.15.0
