name: bao
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.8.3
  - charset-normalizer=3.3.2
  - contourpy=1.3.1
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - expat=2.6.4
  - faiss=1.9.0
  - faiss-gpu=1.9.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - fonttools=4.59.2
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - greenlet=3.1.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libexpat=2.6.4
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=15.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libpq=17.2
  - libsqlite=3.46.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.5.0
  - pathlib=1.0.1
  - pillow=11.0.0
  - pip=24.2
  - psycopg2=2.9.9
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setuptools=72.1.0
  - six=1.17.0
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tikzplotlib=0.10.1
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - webcolors=24.11.1
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - attrs==25.3.0
      - dotenv==0.9.9
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - lightning==2.5.1
      - lightning-utilities==0.14.2
      - multidict==6.2.0
      - packaging==24.2
      - propcache==0.3.1
      - python-dotenv==1.2.1
      - pytorch-lightning==2.5.1
      - sympy==1.13.1
      - torchmetrics==1.7.0
      - tqdm==4.67.1
      - yarl==1.18.3
