title = "Template 4"
# combining toml3 + JOB 1a template

[base_sql]
sql = '''SELECT MIN(mc.note) AS production_note, MIN(t.title) AS movie_title, MIN(t.production_year) AS movie_year
FROM company_type AS ct,
info_type AS it,
movie_companies AS mc,
movie_info_idx AS mi_idx,
title AS t
WHERE ct.kind = 'production companies'
AND it.info = 'top 250 rank'
AND ct.id = mc.company_type_id
AND t.id = mc.movie_id
AND t.id = mi_idx.movie_id
AND mc.movie_id = mi_idx.movie_id
AND it.id = mi_idx.info_type_id;
AND (Xnote1)
AND (mc.note LIKE '%(co-production)%' OR mc.note LIKE '%(presents)%')
```

# template 1
[[templates]]

  name = "1a"

  [[templates.predicates]]
  type = "sql"
  columns = ["mc.note"]
  keys = ["Xnote1"]
  pred_type = "NOT ILIKE"
  sampling_method = "quantile"
  dependencies = 0
  sampling_method = "quantile"
  thresholds = [1000, 2000, 4000, 8000, 20000, 40000]
  min_count = 500
  min_chars = 2
  max_chars = 10
  sql = '''
    SELECT (mc.note)
    FROM movie_companies AS mc
  '''